version: 2.1

jobs:
  core:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Configure
          command: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - run:
          name: Build
          command: cmake --build build --parallel
      - run:
          name: Core tests without native UI
          command: |
            timeout 30s \
              ctest --test-dir build --output-on-failure --label-exclude ui --timeout 15
workflows:
  build:
    jobs:
      - core
